### ISSUE TITLE
Update sketchbook documentation for running GUI from Processing

### ISSUE THREAD

**Issue by philippitts** [OpenBCI/Documentation#112]
In the [Running OpenBCI GUI from Processing](https://docs.openbci.com/Software/OpenBCISoftware/GUIDocs/#running-the-openbci-gui-from-the-processing-ide) section, the documentation states that the source can be placed in sketchbook directory *or anywhere you like*. The source must be placed in the sketchbook folder, but that folder can be moved to any directory you like via `File` -> `Preferences`. If this is done, it is essential that the libraries be copied into a folder called "libraries" in the new sketchbook directory, not the default directory provided in the docs.

Recommend updating the documentation to show how a) use the default sketchbook directory and b) use a custom sketchbook directory.

**Comment by retiutut** [comment]
Fixed in #115
