### ISSUE TITLE
FR: add doc for data file format

### ISSUE THREAD

**Issue by ggrrll** [OpenBCI/Documentation#124]
Hi, 

thanks for the tool.

It would be useful to have a description of the exported data file, e.g. the columns meaning, etc...

thanks 

(maybe here? https://docs.openbci.com/Cyton/CytonDataFormat/ )

**Comment by retiutut** [comment]
This is an important task that can help all users.

Another detail to include is the units, which are microvolts. All data saved to file is unfiltered.

**Comment by retiutut** [comment]
Replace this div on the GUI doc with more info: https://docs.openbci.com/Software/OpenBCISoftware/GUIDocs/#cyton-other-channels

Make sure to include existing information
