### ISSUE TITLE
Shop page broken link

### ISSUE THREAD

**Issue by DashBarkHuss** [OpenBCI/Documentation#127]
The shop page for [ten20 paste](https://shop.openbci.com/collections/frontpage/products/ten20-conductive-paste-8oz-jar) has a broken link where it says "refer to this [guide](https://www.aset.org/files/public/10-20_System_Demonstration.pdf) on parting the hair for 10-20"

broken link: https://www.aset.org/files/public/10-20_System_Demonstration.pdf

I think the link is supposed to be: http://aset.org/wp-content/uploads/2022/01/10-20_System_Demonstration.pdf

Not sure if the shop pages are open source, I couldn't find them on here.

**Comment by retiutut** [comment]
We are fixing this now! Thanks for bringing this to our attention 😸
