### ISSUE TITLE
Erroneous descriptions in Documentation?

### ISSUE THREAD

**Issue by Otemo** [OpenBCI/Documentation#13]
I have found some confusing descriptions in the “Documentation” OpenBCI recently renewed.

1 [Setting up for EEG ](https://docs.openbci.com/docs/01GettingStarted/02-Biosensing-Setups/EEGSetup)

In the table describing how to connect the electrodes to the Gannglion board, there is a description I cannot understand.
There are no "SRB" and "Bias" pins on the Ganglion board.
Here is my idea !

![fig](https://user-images.githubusercontent.com/38579786/67167007-f2468b00-f3cf-11e9-8982-093dfab09420.png)

2 [Ganglion Specs ](https://docs.openbci.com/docs/03Ganglion/GanglionSpecs)

The documentations in the website tells us to connect the ground electrode to **Both** the top **And** bottom of the D_G pin. The similar explanations are given for the REF pin.
However in another web pages, they tell me i need to connect **One** electrode to the top D_G (REF) pin.

・[Headband-Ganglion Tutorial ](https://docs.openbci.com/docs/04AddOns/01-Headwear/HeadBand#headband-ganglion-tutorial)

Does it mean i may connect to the top **OR** bottom of D_G (REF) pin?
I suppose it is enough to connect the ground(reference) electrodes to the top **OR** bottom pins.

I think i have been badly mistaken... ??
I would appreciate knowing more about it.

**Comment by Otemo** [comment]
The support team solved the # 1 problem. 
Thank you so much. 

・EEG setup with Ganglion:
https://docs.openbci.com/docs/01GettingStarted/02-Biosensing-Setups/EEGSetup#1-connect-your-electrodes-to-openbci

・EMG setup with Ganglion:
https://docs.openbci.com/docs/01GettingStarted/02-Biosensing-Setups/EMGSetup#1-connecting-electrodes-to-the-openbci-board

”[Ganglion Specs](https://docs.openbci.com/docs/03Ganglion/GanglionSpecs)” has been still an open question for me.

**Comment by retiutut** [comment]
@Otemo Can this issue be closed?

**Comment by Otemo** [comment]
Hi @retiutut,

Thanks to your support, issue # 1 has been solved.
However, issue # 2(”[Ganglion Specs](https://docs.openbci.com/docs/03Ganglion/GanglionSpecs)”) is still unresolved. 

If you think i have been badly mistaken, please let me know.

**Comment by retiutut** [comment]
From @wjcroft:

Both the schematic and layer diagrams, show that top and bottom pins of D_G and REF are connected together with traces. So makes no difference which you use.
https://docs.openbci.com/docs/assets/GanglionImages/ganglion_schematic.png

**Comment by Otemo** [comment]
Hi @retiutut ,
Thank you for your very polite explanation!
Please close this issue.

@Otemo

**Comment by retiutut** [comment]
About to add this information to the Docs!
