### ISSUE TITLE
Wrong Schematics for Daisy Board

### ISSUE THREAD

**Issue by ValentinPintat** [OpenBCI/Documentation#212]
Hello,
I spent 2 days debuging a daisy board that I recently ordered.
The main page is showing shematics for the daisy board with CLKSEL tied to DVDD.
So in my head the clock was internally generated. 
I had to manually test it with a multimeter to see that the board that I got have CLKSEL tied to AGND.
So please change or edit the schematics so we can see it's actually tied to AGND.
Thank you 
Valentin

**Comment by tharun-OpenBCI** [comment]
Hello Valentin,

Thank you for bringing this to our attention. We'll check the schematics that we have and update this soon
