### ISSUE TITLE
Mark IV Document Cleanup

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/Documentation#37]
https://docs.openbci.com/docs/04AddOns/01-Headwear/MarkIV#completed-8-channel-mark-iv-setup

This doc has missing images, and the following section needs an actual chart, not bulleted points.

>For the remainder of this tutorial, the blue nodes on the 10-20 system diagram (channels 1-8 of the OpenBCI default settings) will be used. The channel to 10-20 system correlations are as follows:
Channel 1(N1P) - Fp1
Channel 2(N2P) - Fp2
Channel 3(N3P) - C3
Channel 4(N4P) - C4
Channel 5(N5P) - P7
Channel 6(N6P) - P8
Channel 7(N7P) - O1
Channel 8(N8P) - O2

Additional clarifications and cleanup as needed.

**Comment by retiutut** [comment]
![Uploading Screen Shot 2020-10-09 at 4.10.22 PM.png…]()

**Comment by retiutut** [comment]
![Screen Shot 2020-10-09 at 4 10 22 PM](https://user-images.githubusercontent.com/25914123/95631857-06a0ef00-0a4a-11eb-809c-41b9bd1b1955.png)

**Comment by evaesteban** [comment]
Updated images and table
