### ISSUE TITLE
Add Documentation for GUI CSV Output and Header

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/Documentation#56]
https://openbci.com/forum/index.php?p=/discussion/2735/understanding-the-csv-headers-of-the-new-v5-gui#latest

This is an easy fix. Should be done ASAP.

**Comment by wjcroft** [comment]
https://openbci.com/forum/index.php?p=/discussion/3288/plotting-analog-read-data-from-gui-recording-file

User confusion would be aided by more documentation. Perhaps the header could include a link to the new doc.

**Comment by wjcroft** [comment]
Forum users still asking for document on CSV format:

https://openbci.com/forum/index.php?p=/discussion/2735/understanding-the-csv-headers-of-the-new-v5-gui#latest

**Comment by retiutut** [comment]
[OpenBCI-RAW-2023-09-01_09-34-21.txt](https://github.com/OpenBCI/Documentation/files/12499079/OpenBCI-RAW-2023-09-01_09-34-21.txt)

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/pull/1182
