### ISSUE TITLE
Combined EEG, EMG, EKG, EOG guide for the Cyton

### ISSUE THREAD

**Issue by evaesteban** [OpenBCI/Documentation#64]
Add a guide with screenshots that show the different types of data being streamed at the same time.

**Comment by retiutut** [comment]
Here is the starting point, which was documented by Conor a long time ago. It was buried in the Cyton Getting Started guide, but this has been deprecated. Belongs in its own new doc.

https://github.com/openbci-archive/Docs/blob/master/Tutorials/01-Cyton_Getting%20Started_Guide.md#v-connect-yourself-to-openbci

**Comment by retiutut** [comment]
Idea from @evaesteban :  

Might be cool to use the Pulse Sensor on a Cyton Aux pin to free up another electrode. 

👍
