### ISSUE TITLE
sudo access for changing FTDI and timestamp problem

### ISSUE THREAD

**Issue by nastaran62** [OpenBCI/Documentation#76]
Hi,

I am using brainflow to stream data from OpenBCI. My problem is when I flush data from buffer, every two or three records which poped from the buffer are the same timestamp. I contacted with brainflow guys and they suggested me to change FTDI buffer settings and changing it from 16 to 1. With this change, timestamps are correct. But the problem is in Linux for changing FTDI buffer I need sudo access. It means I cannot run the code in systems that I don't have sudo access. Also, each time I connect dongle to USB port, I should again set the FTDI buffer. Do you have any solution for this?

**Comment by retiutut** [comment]
>Also, each time I connect dongle to USB port, I should again set the FTDI buffer.

When doing the FTDI buffer fix for Linux, I've never had to re-apply the fix. So this is not really reproducible.
