### ISSUE TITLE
Update external trigger example

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/Documentation#91]
The Cyton External Trigger doc needs to be cleaned up to reflect what actually works and has been learned. It should also be updated to point to the OpenBCI Video Experiment doc (mentioned below).

 https://docs.openbci.com/Cyton/CytonExternal/

Optoisolation and using a photodiode pressed against the screen are two functional methods.

We also have an experiment that uses a photodiode (involving visual stimuli of puppies and kittens). Maybe this doc could be changed slightly (title + mentioning it uses external trigger a little more) to further increase clarity. The purpose of this doc is to show one reliable use-case for an external trigger using a photodiode. This doc also highlights how to time-lock sync visual stimuli.

https://docs.openbci.com/Examples/VideoExperiment/

**Comment by retiutut** [comment]
@wjcroft Shared new title idea for Video Experiment to “P300 Oddball tutorial, using external trigger”.

**Comment by philippitts** [comment]
Let's track updating the external triggers documentation on [this new issue](https://github.com/OpenBCI/Documentation/issues/177), and have this one focus on updating the photodiode example.

**Comment by retiutut** [comment]
I think we can leave the Video Experiment doc as it is for now. The idea here was to point to the use case and lessons learned in the Video Experiment project.

Marking this as a duplicate and moving info to the updated ticket.
